openapi: 3.2.0
info:
  title: Kriya Onboarding Onboarding Journey API
  description: '# Introduction

    Welcome to Onboarding API, an extension to the existing KriyaPaymentsApi platform that allows partners to automate onboarding process, and to view results of these checks in a simple way.'
  contact:
    name: Support
    url: https://kriya.co/
    email: apisupport@kriya.co
  version: ''
  x-logo:
    url: https://cdn.kriya.co/images/Kriya-Putty-Large.svg
    backgroundColor: '#00283C'
    altText: Kriya Logo
servers:
- url: https://api.kriya.dev/onboarding/
  description: Test Environment
- url: https://api.kriya.co/onboarding/
  description: Production Environment
tags:
- name: OnboardingJourney
paths:
  /create:
    get:
      tags:
      - OnboardingJourney
      summary: Create a blank Onboarding Journey without any details
      description: Create a blank Onboarding Journey without any details. However, if an Onboarding Journey already exists and all its associated additional Checks remain incomplete (either not initiated or in 'Pending' or 'Submitted' statuses), a new journey won't be initiated. Instead, the response will provide a link to the pre-existing journey.
      operationId: CreateBlankOnboardingJourney
      responses:
        '302':
          description: No description
          x-ms-summary: Redirects to newly created or preexisting Onboarding Journey
