openapi: 3.2.0
info:
  title: Kriya Payments API
  description: '# Introduction

    Welcome to Kriya Payments API, the platform that allows partners to offer a Buy Now Pay Later (BNPL) payment scheme to their business customers.'
  contact:
    name: Support
    url: https://kriya.co/
    email: apisupport@kriya.co
  version: ''
  x-logo:
    url: https://cdn.kriya.co/images/Kriya-Putty-Large.svg
    backgroundColor: '#00283C'
    altText: Kriya Logo
servers:
- url: http://localhost:7071/api
- url: https://api.kriya.dev/payments/
  description: Test Environment
- url: https://api.kriya.co/payments/
  description: Production Environment
tags:
- name: Payments
paths:
  /payments/deduction:
    post:
      tags:
      - Payments
      summary: Registers a payment deduction for an invoice
      description: Registers a payment deduction to reduce the outstanding balance of an invoice due to credit notes or external repayments.
      operationId: CreatePaymentDeduction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createPaymentDeductionRequest'
      responses:
        '201':
          description: Details of the newly created payment deduction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createPaymentDeductionResponse'
        '401':
          description: Invalid API Key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '400':
          description: The request body could not be understood by the server or contains semantic errors. The response body provides details of the specific reason for the error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '409':
          description: Provided data result in a conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '500':
          description: Something went wrong, please get in touch with tech team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
  /payments/deduction/{paymentIdentifier}:
    get:
      tags:
      - Payments
      summary: Retrieves payment deduction information
      description: Retrieves detailed information about a specific payment deduction using its identifier.
      operationId: GetPaymentDeduction
      parameters:
      - name: paymentIdentifier
        in: path
        description: Unique identifier of the payment deduction assigned by Kriya.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Payment deduction details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentDeductionResponse'
        '401':
          description: Invalid API Key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '404':
          description: The resource with this identifier was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '500':
          description: Something went wrong, please get in touch with tech team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
  /payments/deductions:
    get:
      tags:
      - Payments
      summary: Fetches list of payment deductions
      description: Fetches a list of existing payment deductions with optional filters.
      operationId: ListPaymentsDeductions
      parameters:
      - name: InvoiceReferenceNumber
        in: query
        description: Invoice reference number to filter by.
        schema:
          type: string
      - name: PaymentDeductionStatus
        in: query
        description: Payment status to filter by.
        schema:
          enum:
          - applied
          - processed
          type: string
          default: applied
      responses:
        '200':
          description: List of existing payment deductions. Only 100 of the most recent payments are returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/paymentDeductionResponse'
        '401':
          description: Invalid API Key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '500':
          description: Something went wrong, please get in touch with tech team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
components:
  schemas:
    createPaymentDeductionResponse:
      type: object
      properties:
        buyer:
          $ref: '#/components/schemas/paymentDeductionBuyer'
        paymentIdentifier:
          type: string
          description: The unique identifier for the payment deduction assigned by Kriya. It can be used to retrieve the payment deduction details using the Kriya Payments API Get endpoint.
        type:
          enum:
          - CreditNote
          - Dispute
          - DirectPayment
          type: string
          description: Reason to create payment deduction.
        invoiceReferenceNumber:
          type:
          - string
          - 'null'
          description: Invoice reference number.
        processType:
          enum:
          - AdvanceDeduction
          type: string
          description: The method of settling payment deduction.
        payment:
          $ref: '#/components/schemas/monetaryValue'
        status:
          enum:
          - Applied
          - Processed
          type: string
          description: The settlement status of the payment deduction. Applied means Kriya has not received the full deduction amount from the merchant. Processed means Kriya has received the full deduction amount.
        createdOn:
          type: string
          description: Date when the payment deduction has been applied.
          format: date-time
        processedOn:
          type:
          - string
          - 'null'
          description: Date when status of the payment deduction has changed to Processed.
          format: date-time
        paymentReference:
          type: string
          description: Human readable reference of the payment deduction.
    createPaymentDeductionRequest:
      type: object
      properties:
        type:
          enum:
          - CreditNote
          - DirectPayment
          type: string
          description: Reason to create payment deduction.
        invoiceReferenceNumber:
          type: string
          description: 'InvoiceReference or MerchantOrderId.

            If multiple orders have the same InvoiceReference, using InvoiceReference will reduce the balance of the oldest outstanding order. Use MerchantOrderId to reduce the balance of a specific order.'
        processType:
          enum:
          - AdvanceDeduction
          type: string
          description: The method of settling payment deductions. AdvanceDeduction refers to Kriya deducting the amount from the next available advance funds.
          default: AdvanceDeduction
        payment:
          $ref: '#/components/schemas/monetaryValue'
        creditNoteNumber:
          type:
          - string
          - 'null'
          description: Credit note number. Mandatory if Type is CreditNote.
        paymentType:
          enum:
          - None
          - Bank
          - Card
          - Cheque
          - Digital
          type:
          - string
          - 'null'
          description: Type of the payment. Mandatory if Type is DirectPayment.
        uniqueKey:
          type:
          - string
          - 'null'
          description: This is an optional field to prevent the creation of duplicate payment deductions. If the UniqueKey already exists, the payment deduction will fail with a 409 error.
    monetaryValue:
      required:
      - amount
      - currency
      type: object
      properties:
        amount:
          type: integer
          description: The total value adjustment registered on the invoice level.
          format: int64
        currency:
          enum:
          - GBP
          - EUR
          - USD
          type: string
          description: The ISO 4217 currency of the order
      description: The payment deduction amount.
    paymentDeductionBuyer:
      type: object
      properties:
        totalLimit:
          type: integer
          description: The total limit given to the buyer.
          format: int64
        availableLimit:
          type: integer
          description: The available limit remaining for the buyer.
          format: int64
        usedLimit:
          type: integer
          description: The total limit currently utilised across all active orders.
          format: int64
      description: Current buyer limits.
    problemDetails:
      type: object
      properties:
        title:
          type: string
          description: The high level message returned for an non-success response.
        message:
          type: string
          description: A description of the issue.
        errors:
          type: array
          items:
            type: string
          description: The individual errors that caused the non-success response.
        date:
          type: string
          description: The date and time at which the errors occured.
          format: date-time
        operationId:
          type: string
          description: The unique identifier for the operation where the error was caused. This will be of use and should be provided when requesting further support.
    paymentDeductionResponse:
      type: object
      properties:
        paymentIdentifier:
          type: string
          description: The unique identifier for the payment deduction assigned by Kriya. It can be used to retrieve the payment deduction details using the Kriya Payments API Get endpoint.
        type:
          enum:
          - CreditNote
          - Dispute
          - DirectPayment
          type: string
          description: Reason to create payment deduction.
        invoiceReferenceNumber:
          type:
          - string
          - 'null'
          description: Invoice reference number.
        processType:
          enum:
          - AdvanceDeduction
          type: string
          description: The method of settling payment deduction.
        payment:
          $ref: '#/components/schemas/monetaryValue'
        status:
          enum:
          - Applied
          - Processed
          type: string
          description: The settlement status of the payment deduction. Applied means Kriya has not received the full deduction amount from the merchant. Processed means Kriya has received the full deduction amount.
        createdOn:
          type: string
          description: Date when the payment deduction has been applied.
          format: date-time
        processedOn:
          type:
          - string
          - 'null'
          description: Date when status of the payment deduction has changed to Processed.
          format: date-time
        paymentReference:
          type: string
          description: Human readable reference of the payment deduction.
